# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
#  - name: Tour
#    url: tour
#    weight: 10
  - name: People
    url: people
    weight: 30
  - name: Meetings
    url: meetings
    weight: 40
  - name: Joint Efforts
    url: publication
    weight: 50
  - name: NIMSS
    url: https://www.nimss.org/projects/view/mrp/outline/18798
    weight: 60
  - name: Contact
    url: contact
    weight: 70
